// src/ui/src/views/IssuePanel.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import { view } from '@forge/bridge';
import { getFlagsForIssue, toggleFlag } from '../api';
import type { Environment, FlagRow } from '../types';
import FlagTable from '../components/FlagTable.vue';
import CreateFlagModal from '../components/CreateFlagModal.vue';
import LinkFlagModal from '../components/LinkFlagModal.vue';
import ToastMessage from '../components/ToastMessage.vue';
import { useToast } from '../composables/useToast';

type Modal = 'create' | 'link' | null;

const issueKey = ref<string | null>(null);
const flags = ref<FlagRow[]>([]);
const environments = ref<Environment[]>([]);
const portalUrl = ref<string | undefined>(undefined);
const canCreateFlag = ref(true);
const readOnlyEnvIds = ref<string[]>([]);
const loading = ref(true);
const error = ref<string | null>(null);
const toggling = ref(new Set<string>());
const modal = ref<Modal>(null);
const panelToast = useToast();

onMounted(() => {
  void view.getContext().then((ctx) => {
    const ext = ctx.extension as { issue?: { key?: string } } | undefined;
    issueKey.value = ext?.issue?.key ?? null;
  });
});

async function load(key: string) {
  loading.value = true;
  error.value = null;
  try {
    const res = await getFlagsForIssue(key);
    if (res.error) {
      error.value = res.error;
    } else {
      flags.value = res.flags ?? [];
      environments.value = res.environments ?? [];
      portalUrl.value = res.portalUrl || undefined;
      canCreateFlag.value = res.canCreateFlag !== false;
      readOnlyEnvIds.value = res.readOnlyEnvIds ?? [];
    }
  } catch (e) {
    error.value = String(e);
  } finally {
    loading.value = false;
  }
}

watch(issueKey, (key) => {
  if (key) void load(key);
});

function handleDone(msg?: string) {
  modal.value = null;
  if (issueKey.value) void load(issueKey.value);
  if (msg) panelToast.show(msg);
}

async function handleToggle(payload: {
  envId: string;
  flagKey: string;
  enable: boolean;
}) {
  const { envId, flagKey, enable } = payload;
  const key = `${envId}:${flagKey}`;
  if (toggling.value.has(key)) return;
  toggling.value.add(key);

  // Optimistic update
  flags.value = flags.value.map((f) => {
    if (f.key !== flagKey) return f;
    return {
      ...f,
      environments: f.environments.map((e) =>
        e.envId === envId ? { ...e, isEnabled: enable } : e
      ),
    };
  });

  const res = await toggleFlag({
    envId,
    flagKey,
    enable,
    issueKey: issueKey.value ?? undefined,
  });
  toggling.value.delete(key);

  if (res.error) {
    panelToast.show(`Toggle failed: ${res.error}`);
    if (issueKey.value) void load(issueKey.value);
  }
}
</script>

<template>
  <div
    v-if="!issueKey"
    class="px-4 py-3 border border-border rounded bg-surface text-text leading-relaxed"
  >
    Could not determine the current issue key.
  </div>

  <div v-else-if="loading" class="p-3 text-text-subtle">Loading flags…</div>

  <div
    v-else-if="error?.includes('not configured')"
    class="px-4 py-3 border border-border rounded bg-surface text-text leading-relaxed"
  >
    FeatBit is not configured.
    <strong>Open the FeatBit Settings global page</strong> to enter your API URL
    and access token.
  </div>

  <div
    v-else-if="error"
    class="px-4 py-3 border border-danger rounded bg-danger-bg text-danger leading-relaxed"
  >
    {{ error }}
  </div>

  <div
    v-else
    class="py-3"
    :style="{ position: 'relative', minHeight: modal ? '520px' : undefined }"
  >
    <ToastMessage
      :message="panelToast.message.value"
      :fading="panelToast.fading.value"
    />

    <div class="flex justify-between items-center mb-3">
      <span class="font-semibold text-sm text-text">
        {{ flags.length }} flag{{ flags.length !== 1 ? 's' : '' }} linked to
        {{ issueKey }}
      </span>
      <div class="flex gap-2">
        <button
          class="px-3 py-1 text-sm font-medium rounded border border-border bg-surface-overlay text-text cursor-pointer"
          @click="modal = 'link'"
        >
          Link existing flag
        </button>
        <button
          v-if="canCreateFlag"
          class="px-3 py-1 text-sm font-medium rounded border border-accent bg-accent text-white cursor-pointer"
          @click="modal = 'create'"
        >
          + Create flag
        </button>
      </div>
    </div>

    <div v-if="flags.length === 0" class="py-6 text-center text-text-subtle">
      <div>No feature flags linked to {{ issueKey }} yet.</div>
      <div class="mt-2 text-xs">
        Create a new flag or link an existing one tagged with
        <strong>{{ issueKey }}</strong
        >.
      </div>
    </div>
    <FlagTable
      v-else
      :flags="flags"
      :environments="environments"
      :portal-url="portalUrl"
      :toggling="toggling"
      :read-only-env-ids="readOnlyEnvIds"
      @toggle="handleToggle"
    />

    <CreateFlagModal
      v-if="modal === 'create'"
      :issue-key="issueKey"
      @close="modal = null"
      @done="handleDone"
    />
    <LinkFlagModal
      v-if="modal === 'link'"
      :issue-key="issueKey"
      @close="modal = null"
      @done="handleDone"
    />
  </div>
</template>

// static/src/views/IssuePanel.tsx
import { useCallback, useEffect, useState } from 'react';
import { view } from '@forge/bridge';
import { getFlagsForIssue } from '../api';
import type { Environment, FlagRow } from '../types';
import FlagTable from '../components/FlagTable';
import CreateFlagModal from '../components/CreateFlagModal';
import LinkFlagModal from '../components/LinkFlagModal';

type Modal = 'create' | 'link' | null;

export default function IssuePanel() {
  const [issueKey, setIssueKey] = useState<string | null>(null);
  const [flags, setFlags] = useState<FlagRow[]>([]);
  const [environments, setEnvironments] = useState<Environment[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [modal, setModal] = useState<Modal>(null);

  useEffect(() => {
    void view.getContext().then((ctx) => {
      const ext = ctx.extension as { issue?: { key?: string } } | undefined;
      setIssueKey(ext?.issue?.key ?? null);
    });
  }, []);

  const load = useCallback(async (key: string) => {
    setLoading(true);
    setError(null);
    try {
      const res = await getFlagsForIssue(key);
      if (res.error) {
        setError(res.error);
      } else {
        setFlags(res.flags ?? []);
        setEnvironments(res.environments ?? []);
      }
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (issueKey) void load(issueKey);
  }, [issueKey, load]);

  const handleDone = () => {
    setModal(null);
    if (issueKey) void load(issueKey);
  };

  if (!issueKey)
    return (
      <div className="px-4 py-3 border border-gray-200 rounded bg-gray-100 text-[#172B4D] leading-relaxed">
        Could not determine the current issue key.
      </div>
    );

  if (loading) return <div className="p-3 text-gray-500">Loading flags…</div>;

  if (error?.includes('not configured')) {
    return (
      <div className="px-4 py-3 border border-gray-200 rounded bg-gray-100 text-[#172B4D] leading-relaxed">
        FeatBit is not configured.{' '}
        <strong>Open the FeatBit Settings global page</strong> to enter your API
        URL and access token.
      </div>
    );
  }

  if (error)
    return (
      <div className="px-4 py-3 border border-red-200 rounded bg-red-50 text-red-700 leading-relaxed">
        {error}
      </div>
    );

  return (
    <div className="py-3">
      <div className="flex justify-between items-center mb-3">
        <span className="font-semibold text-sm text-[#172B4D]">
          {flags.length} flag{flags.length !== 1 ? 's' : ''} linked to{' '}
          {issueKey}
        </span>
        <div className="flex gap-2">
          <button
            className="px-3 py-1 text-sm font-medium rounded border border-gray-300 bg-gray-100 text-[#172B4D] cursor-pointer"
            onClick={() => setModal('link')}
          >
            Link existing flag
          </button>
          <button
            className="px-3 py-1 text-sm font-medium rounded border border-blue-700 bg-blue-700 text-white cursor-pointer"
            onClick={() => setModal('create')}
          >
            + Create flag
          </button>
        </div>
      </div>

      {flags.length === 0 ? (
        <div className="py-6 text-center text-gray-500">
          <div>No feature flags linked to {issueKey} yet.</div>
          <div className="mt-2 text-xs">
            Create a new flag or link an existing one tagged with{' '}
            <strong>{issueKey}</strong>.
          </div>
        </div>
      ) : (
        <FlagTable flags={flags} environments={environments} />
      )}

      {modal === 'create' && (
        <CreateFlagModal
          issueKey={issueKey}
          onClose={() => setModal(null)}
          onDone={handleDone}
        />
      )}
      {modal === 'link' && (
        <LinkFlagModal
          issueKey={issueKey}
          onClose={() => setModal(null)}
          onDone={handleDone}
        />
      )}
    </div>
  );
}
